server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/db/notification
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
