spring:
  application:
    name: ead-course-service
  profiles:
    active: postgress
  #para mostrar as cores do log no cmd
  output:
    ansi:
      enabled: Always

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
